need2fix/app/urls.py
from django.urls import path
from app.views import task_list, task_add, task_detail
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
urlpatterns = [
    path('list/', task_list, name='task-list'),
    path('add/', task_add, name='task-add'),
    path('detail/<int:pk>/', task_detail, name='task-detail'),
    path('logout/', auth_views.logout, name='logout'),
]

need2fix/need2fix/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.routers import router
from app.views import home, task_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', task_list, name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('task/', include(('app.urls', 'app'), namespace='app')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

need2fix/app/models.py
import os
import json
import pytz
from django.utils import timezone
from django.db import models
from django.db import transaction
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from app import building_info, division_list
from simple_history.models import HistoricalRecords

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    history = HistoricalRecords()

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.PROTECT)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    history = HistoricalRecords()

def get_upload_path(instance, filename):
    return os.path.join(instance.requester.username, filename)


usermodel = get_user_model()


class Task(models.Model):
    STATUS_CHOICES = [
        ('1', 'รับเรื่อง'),
        ('2', 'ดำเนินการ'),
        ('3', 'เสร็จสิ้น'),
    ]

    DIVISION_CHOICES = [(k, v) for k, v in division_list.items()]


    title = models.CharField(max_length=64)
    description = models.CharField(max_length=512, null=True, blank=True)
    building = models.CharField(max_length=32)
    floor = models.CharField(max_length=32)
    room = models.CharField(max_length=32)
    contact = models.EmailField(max_length=32)
    phone_contact = models.CharField(max_length=32, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    done_date = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=1, blank=True, choices=STATUS_CHOICES)
    division = models.CharField(max_length=2, blank=True, choices=DIVISION_CHOICES, null=True)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    after_image = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    requester = models.ForeignKey(usermodel, blank=True, on_delete=models.PROTECT, related_name='request_set')
    operator = models.ForeignKey(usermodel, null=True, blank=True, on_delete=models.SET_NULL, related_name='task_set')

    @transaction.atomic
    def save(self, *args, **kwargs):
        if not self.pk:
            self.status = '1'
            if 'user' in kwargs:
                self.requester = kwargs['user']
        self.full_clean()
        if self.status == '3':
            self.done_date = timezone.now()
        super(Task, self).save(*args, **kwargs)
        
    def clean(self, *args, **kwargs):
        if self.status in ('2', '3') and not self.operator:
            raise ValidationError('Null Operator exeption')        
            if self.operator and not self.operator.groups.filter(name='mechanic'):
                raise ValidationError('Operator must be in Mechanic group.')
            
        if self.building in building_info:
            if self.floor in building_info[self.building]:
                pass
            else:
                raise ValidationError('invalid floor available floor are {}'\
                    .format(list(building_info[self.building])))
        else:
            raise ValidationError('invalid building available building are {}'\
                .format(list(building_info)))
        return True
        # if self.building in building_info:
        #     if self.floor in building_info[self.building]:
        #         if self.room in building_info[self.building][self.floor]:
        #             pass
        #         else:
        #             raise ValidationError('invalid room available room are {}'\
        #                 .format(list(building_info[self.building][self.floor])))
        #     else:
        #         raise ValidationError('invalid floor available floor are {}'\
        #             .format(list(building_info[self.building])))
        # else:
        #     raise ValidationError('invalid building available building are {}'\
        #         .format(list(building_info)))
        # return True

need2fix/app/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.admin import widgets
from app.models import Task

class TaskForm(ModelForm):

    class Meta:
        model =  Task
        fields = ('status', )

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

need2fix/app/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from app.models import Task

#@login_required
def task_list(request):
    return render(request, 'app/task_list.html')

@login_required
def task_add(request):
    return render(request, 'app/task_add.html')

@login_required
def task_detail(request, pk):
    context = {'pk': pk}
    return render(request, 'app/task_detail.html', context)


def home(request):
    return render(request, 'app/home.html')

need2fix/app/templates/app/home.html
<!--{% extends 'base.html' %}
{% block title %} แจ้งซ่อม {% endblock %}
{% block content %}
<div id="content">
    วิธีใช้งาน
</div>
{% endblock %}

{% block script %}
{% endblock %}*/-->

need2fix/app/templates/app/task_add.html
{% extends 'base.html' %}
{% block title %} แจ้งซ่อม {% endblock %}
{% block content %}
<div style="margin:50px;">
<div id='content' style="margin-top:5%">
  <form class="uk-form-horizontal">
    <fieldset class="uk-fieldset">
      <legend class="uk-legend"> กรุณากรอกข้อมูลแจ้งซ่อม </legend>
      <div class="uk-margin">
        <input class="uk-input" type="text" placeholder="หัวเรื่อง" v-model="formInput.title">
      </div>
      <div class="uk-margin">
        <label> ถึง </label>
        <select class="uk-select" v-model="formInput.division">
          <option v-for="(description, division) in divisionList" v-bind:value="division"> [[description]] </option>
        </select>
      </div>
      <div class="uk-margin">
        <textarea class="uk-textarea" rows="5" placeholder="คำธิบาย" v-model="formInput.description"></textarea>
      </div>
      <div class="uk-margin">
        <label> อาคาร </label>
        <select class="uk-select" v-model="formInput.building">
          <option v-for="(info, building) in buildingInfo"> [[building]] </option>
        </select>
      </div>
      <div class="uk-margin" v-if="formInput.building">
        <label> ชั้น </label>
        <select class="uk-select" v-model="formInput.floor">
          <option v-for="(info, floor) in buildingInfo[formInput.building]"> [[floor]] </option>
        </select>
      </div>
      <div class="uk-margin" v-if="formInput.floor">
        <label> ห้อง </label>
        <div class="uk-margin">
          <input class="uk-input" type="text" placeholder="ห้อง" v-model="formInput.room" required>
        </div>
        <!-- <select class="uk-select" v-model="formInput.room">
          <option v-for="room in buildingInfo[formInput.building][formInput.floor]"> [[room]] </option>
        </select> -->
      </div>
      <div class="uk-margin">
        <label> ติดต่อกลับ </label>
        <div class="uk-margin">
          <input class="uk-input" type="email" placeholder="e-mail" v-model="formInput.contact" required>
        </div>
      </div>
      <div class="uk-margin" v-if="formInput.contact">
        <label> หมายเลขโทรศัพท์ </label>
        <div class="uk-margin">
          <input class="uk-input" type="text" placeholder="กรณีที่ต้องการให้โทรติดต่อกลับไปเมื่อซ่อมสำเร็จแล้ว" v-model="formInput.phone_contact">
        </div>
      </div>
      <div class="js-upload" uk-form-custom>
        <input type="file" ref='imageUpload' v-on:change="imageHandle()">
        <button class="uk-button uk-button-default" type="button" v-if="imageFile==null" tabindex="-1">เพิ่มรูปภาพ</button>
        <button class="uk-button uk-button-default" type="button" v-if="imageFile!=null" tabindex="-1">เปลี่ยนรูปภาพ</button>

      </div>
      <button class="uk-button uk-button-default" type="button" tabindex="-1" v-if="previewImage" v-on:click="clearImage">ล้าง</button>
      <image class="imagePreviewer" v-bind:src="previewImage" v-if="imageFile!=null"> </image>
    </fieldset>
  </form>
  <br>
  <button class="uk-button uk-button-default" v-on:click="submitRequest()"  v-bind:disabled="checkSubmitable() ">ส่งคำร้อง</button>
</div>
</div>

<style type="text/css">
  .imagePreviewer {
    width: 400px;
    background-color: white;
    border: 1px solid #DDD;
    padding: 5px;
  }
</style>

{% endblock %}

{% block script %}
<script type="text/javascript">
new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],

  mounted () {
    axios.get('/api/building-info')
      .then((res) => {
        this.buildingInfo = res.data
      })
    axios.get('/api/division-list')
      .then((res) => {
        this.divisionList = res.data
        this.divisionList[null] = "ไม่ระบุ"
      })
  },

  data: function () {
    return {
      'buildingInfo': {},
      'divisionList': {},
      'formInput': {},
      'imageFile': null,
      'previewImage': null
    }
  },

  methods: {
    clearImage: function () {
      this.previewImage = null
      this.imageFile = null
    },

    imageHandle: function() {
      this.imageFile = this.$refs.imageUpload.files[0]
      var reader = new FileReader();
        reader.onload = (e) => {
          this.previewImage = e.target.result;
        }
        reader.readAsDataURL(this.imageFile);
    },

    checkSubmitable: function() {
      let checklist = ['title', 'building', 'floor', 'room', 'contact']
      try{
        checklist.forEach( (d) => {
          if (this.formInput[d]== null) throw BreakException
        })
        return false
      } catch (e) {
        return true
      }
    },

    clearForm: function () {
      this.formInput.title = ''
      this.formInput.description = ''
      this.formInput.building = ''
      this.formInput.floor = ''
      this.formInput.room = ''
      this.formInput.contact = ''
      this.clearImage()
    },

    submitRequest: function () {

      let formData = new FormData()
      for (let key in this.formInput ) {
        if (this.formInput[key] != "null") {
          formData.set(key, this.formInput[key])
        }
      }
      if (this.imageFile) {
        formData.set('image', this.imageFile)
      } 

      axios.post('/api/task/', formData)
        .then((res) => {
          alert('ส่งคำร้องเรียบร้อย')
          window.location = "/task/list";
        })
        .catch((error) => {
          s = 'เกิดข้อผิดพลาด'
          for(let k in error.response.data) {
            s += '\n' + k + ': ' + error.response.data[k]
          }
          alert(s)

        })
    }
  }
})
</script>
{% endblock %}

need2fix/app/templates/app/task_detail.html
{% extends 'base.html' %}
{% block title %} งานซ่อม {% endblock %}
{% block content %}
  <div style="margin:50px;">
  <div id='content'>
    <!-- Editable  -->
    <form class="uk-form-horizontal">
      <fieldset class="uk-fieldset">
        <legend class="uk-legend"> คำร้องที่ {{pk}} </legend>
        {%if user.is_staff%}
            <label>สถานะ</label>
            <select select class="uk-select" v-model="formData.status" >
              <option value="1">รับเรื่อง</option>
              <option value="2">ดำเนินการ</option>
              <option value="3">เสร็จสิ้น</option>
            </select>
            <label>ผู้รับผิดชอบ</label>
            <select select class="uk-select" v-model="formData.operator" >
              <option v-for="mec in mechanicList" v-bind:value="mec.id" > [[mec.first_name]] [[mec.last_name]] </option>
            </select>
            <!-- <br><br>
            <div class="js-upload" uk-form-custom>
              <input type="file" ref='imageUpload' v-on:change="imageHandle()">
              <button class="uk-button uk-button-default" type="button" v-if="imageFile==null" tabindex="-1">เพิ่มรูปภาพ</button>
              <button class="uk-button uk-button-default" type="button" v-if="imageFile!=null" tabindex="-1">เปลี่ยนรูปภาพ</button>
            </div>
            <button class="uk-button uk-button-default" type="button" tabindex="-1" v-if="previewImage" v-on:click="clearImage">ล้าง</button>
            <image class="imagePreviewer" v-bind:src="previewImage" v-if="imageFile!=null"> </image> -->
        {%else%}
            <label>สถานะ</label>
            <select select class="uk-select" v-model="formData.status" disabled>
              <option value="1">รับเรื่อง</option>
              <option value="2">ดำเนินการ</option>
              <option value="3">เสร็จสิ้น</option>
            </select>
            <label>ผู้รับผิดชอบ</label>
            <select select class="uk-select" v-model="formData.operator" disabled>
              <option v-for="mec in mechanicList" v-bind:value="mec.id" > [[mec.first_name]] [[mec.last_name]] </option>
            </select>
        {%endif%}

      </fieldset>
    </form>

    {%if user.is_staff%}
    <button class="uk-button uk-button-default" style="margin-top:10px " v-on:click="updateRequest()">ส่งคำร้อง</button>
    {%endif%}

    <!-- ReadOnly -->
    <div class="uk-margin"  >
      <label >หัวเรื่อง</label>
      <input class="uk-input" type="text" placeholder="หัวเรื่อง" v-model="formData.title" disabled>
    </div>
    <div class="uk-margin">
      <label> ถึง: [[divisionName]] </label>
    </div>
    <div class="uk-margin">
      <label>คำอธิบาย</label>
      <textarea class="uk-textarea" rows="5" placeholder="คำธิบาย" v-model="formData.description" disabled></textarea>
    </div>
    <div class="uk-margin">
      <label> อาคาร: [[formData.building]] </label>
    </div>
    <div class="uk-margin">
      <label> ชั้น: [[formData.floor]] </label>
    </div>
    <div class="uk-margin">
      <label> ห้อง: [[formData.room]] </label>
    </div>
    <div class="uk-margin">
      <label> ติดต่อกลับ: [[formData.contact]] </label>
    </div>
    <div class="uk-margin">
      <label> หมายเลขโทรศัพท์: [[formData.phone_contact]] </label>
    </div>
    <image class="imagePreviewer" v-bind:src="formData.image" v-if="formData.image!=null"> </image>
    <image class="imagePreviewer" v-bind:src="formData.after_image" v-if="formData.after_image!=null"> </image>
  </div>
  </div>
  <style type="text/css">
    .imagePreviewer {
      width: 400px;
      background-color: white;
      border: 1px solid #DDD;
      padding: 5px;
    }
  </style>
{% endblock %}

{% block script %}
<script type='text/javascript'>
var content = new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],

  data: function () {
    return {
      'formData': {},
      'divisionList': {},
      'mechanicList': [],
      'imageFile': null,
      'previewImage': null
    }
  },
  
  computed: {
    divisionName: function () {
      return this.formData.division? this.divisionList[this.formData.division]: 'ไม่ระบุ'
    }
  },

  mounted: function () {
    axios.get('/api/division-list/')
      .then((response) => {
        this.divisionList = response.data
      })
      .catch((error) => {
        alert(error)
      })    
    axios.get('/api/mechanic-list/')
      .then((response) => {
        this.mechanicList = response.data
      })
      .catch((error) => {
        alert(error)
      })
    axios.get('/api/task/'+'{{pk}}/')
      .then((response) => {
        this.formData = response.data
        formData = response.data
      })
      .catch((error) => {
        alert(error)
      })
  }, 

  methods: {
    clearImage: function () {
      this.previewImage = null
      this.imageFile = null
    },

    imageHandle: function() {
      this.imageFile = this.$refs.imageUpload.files[0]
      var reader = new FileReader();
        reader.onload = (e) => {
          this.previewImage = e.target.result;
        }
        reader.readAsDataURL(this.imageFile);
    },

    updateRequest: function () {
      if (confirm("ยืนยันการแก้ไข")) {
        
        console.log(this.formData)
        axios.patch('/api/task/'+'{{pk}}/', {
              'status': this.formData.status,
              'operator': this.formData.operator,
              // 'after_image':this.imageFile
          })
        
          .then((response) => {
            console.log(response.data)
            window.location ='/task/list';
          })
          .catch((error) => {
            console.log('ล้มเหลว1')
            s = 'เกิดข้อผิดพลาด'
            for(let k in error.response.data) {
              s += '\n' + k + ': ' + error.response.data[k]
            }
            alert(s)
          })
      }
    }
  }

})
</script>
{% endblock %}

need2fix/app/templates/app/task_list.html
{% extends 'base.html' %}
{% block title %} งานซ่อม {% endblock %}
{% block content %}
<div style="margin:50px;">
<div id='content' style="margin-top:5%">
  <form  style="text-align:center">
    <input type='radio' value='0' v-model='filterStatus' > ทั้งหมด 
    <input type='radio' value='1' v-model='filterStatus'style="margin-left:3%"> รับเรื่อง
    <input type='radio' value='2' v-model='filterStatus'style="margin-left:3%"> ดำเนินการ
    <input type='radio' value='3' v-model='filterStatus'style="margin-left:3%"> เสร็จสิ้น
  </form>
  {% if user.is_authenticated %}
  <form>
    <input type='checkbox' value='true' v-model='onlyMe' style="margin-left:5%"> งานของฉัน
  </form>
  {% endif %}
  <table class='uk-table uk-table-striped uk-table-hover uk-table-small'>
    <caption style="margin-left:1%; font-size: 16px;">งานแจ้งซ่อม</caption>
    <thead>
      <tr style="background-color:#c00832;margin-left:3%;" >
        <th style="color:white; font-size: 16px;"> หัวเรื่อง </th>
        <th style="color:white; font-size: 16px;"> ฝ่าย </th>
        <th style="color:white; font-size: 16px;"> คำอธิบาย </th>
        <th style="color:white; font-size: 16px;"> ตึก </th>
        <th style="color:white; font-size: 16px;"> ชั้น </th>
        <th style="color:white; font-size: 16px;"> ห้อง </th>
        <th style="color:white; font-size: 16px;"> สถานะ </th>
      </tr>
    </thead>
    <tbody v-for='task in taskList' >
      <tr v-if='(onlyMe==false & (filterStatus==0 | task.status==filterStatus)) |
                ({{user.id}}!="None" & onlyMe==true & 
                  (filterStatus==0 | task.status==filterStatus) & 
                  (task.requester=={{user.id}} | task.operator=={{user.id}})
                )'>
        <td> <a v-bind:href="'/task/detail/'+task.id+'/'">[[task.title]]</a></td>
        <td>[[divisionName(task.division)]]</td>
        <td>[[task.description]]</td>
        
        <td>[[task.building]]</td>
        <td>[[task.floor]]</td>
        <td>[[task.room]]</td>
        <td>[[task.status==1? 'รับเรื่อง':task.status==2?'ดำเนินการ':'เสร็จสิ้น']]</td>
      </tr>
    </tbody>
  </table>
</div>
</div>
<style>
    td{
      width: 100px;
      max-width: 250px; /* add this */
      white-space: nowrap;
      overflow: hidden;
    }
</style>
{% endblock %}

{% block script %}
<script type='text/javascript'>
var content = new Vue({
  el: '#content',
  delimiters: ['[[', ']]'],
  data: function () {
    return {
      'message': 'Hello',
      'taskList': null,
      'filterStatus': 1,
      'onlyMe': false,
      'divisionList': []
    }
  },

  methods: {
    divisionName: function (division) {
      return division? this.divisionList[division]: 'ไม่ระบุ'
    }
  },

  mounted: function () {
    axios.get('/api/task/')
      .then((response) => {
        this.taskList = response.data
      })
      .catch((error) => {
        alert(error)
      })
    axios.get('/api/division-list/')
      .then((response) => {
        this.divisionList = response.data
      })
      .catch((error) => {
        alert(error)
      })   
  }
})
</script>
{% endblock %}

need2fix/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title> {% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/uikit.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit:300,400,500,700&amp;subset=thai">
  <link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
  <link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/css/froala_style.min.css' rel='stylesheet' type='text/css' />
  <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.8.4/js/froala_editor.min.js'></script>
  <script src="https://analytics.service.sci.tu.ac.th/static/js/access.js"></script>
 
</head>

<body>
<script src="{% static 'js/vue.js' %}"></script>
<script src="{% static 'js/axios.min.js' %}"></script>
<script type="text/javascript">
  axios.defaults.headers.common['X-CSRFToken'] = '{{csrf_token}}'
</script>
<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
<script src="{% static 'js/uikit.min.js' %}"></script>
<script src="{% static 'js/uikit-icons.min.js' %}"></script>

<div id="app">
    <div class="body-block">
      <!-- header section -->
      <div class="navbar">
        <div class="header" >
          <nav class="uk-navbar-container" uk-navbar="mode: click">
            <div class="uk-navbar-left">
              <!-- <img src="static/main-logo.svg" class="main-logo"> -->
              <a href="/"><img src="{% static 'img/scitu_logo.svg' %}" class="main-logo"></a> 
            
            </div>
            <div class="uk-navbar-right" style="margin-right:5%;">
            {% if user.is_authenticated %}
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav uk-visible@l">
                    <li> <a href="{% url 'app:task-list' %}"> สถานะคำร้อง </a> </li>
                    <li> <a href="{% url 'app:task-add' %}"> สร้างคำร้องใหม่ </a> </li>
                    <!-- <li  class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid style=" padding: 10px;">
                        <img class="uk-comment-avatar" src="{% static 'avatar.png' %}" alt="" >
                        <h3 class="uk-comment-title uk-margin-remove">{{user.username}}</h3>

                    </li> -->
                    <article class="uk-comment">
                        <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                          <div class="uk-width-auto">
                            <img class="uk-comment-avatar" src="{% static 'img/avatar.png' %}" alt="">
                          </div>
                          <div class="uk-width-auto">
                            <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset" href="#" > {{user.username}} </a></h4>
                            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                              <!-- <li><a href="#" style="color:white">setting</a></li> -->
                              <li><a href="/api-auth/logout/" >logout</a></li>
                            </ul>
                          </div>
                        </header>
                      </article>
                </ul>
              <div class="dropdown uk-hidden@l">
                  <a class="uk-navbar-toggle" uk-navbar-toggle-icon></a>
                  <div uk-dropdown="pos: bottom-right; mode: click; animation: uk-animation-slide-top-small; duration: 500">
                    <ul class="uk-nav uk-dropdown-nav">
                        <li> <a href="{% url 'app:task-list' %}"> สถานะคำร้อง </a> </li>
                        <li> <a href="{% url 'app:task-add' %}"> สร้างคำร้องใหม่ </a> </li>
                    </ul>
                  </div>
                </div>
              </div>

              {% else %}
            <div class="uk-navbar-right" >
              <form action="{% url 'social:begin' 'tu' %}">
                <input class="uk-button uk-button-primary" type="submit" value='TU LOGIN'>
              </form>
            </div>
            {% endif %}
          
          </nav>
        </div>
      </div>
      <div class="uk-margin-remove-bottom" align="center" style="background-color:#c00832;"><h3 style="color:white;">ระบบแจ้งซ่อม</h3></div>
    
{% block content %} {% endblock %}


<div class="page-footer">
  <div class="uk-flex footer-flex">
      <div class="about">
          <div class="contact">
              <h6 class="contact-text">ติดต่อธรรมศาสตร์</h6>
              <ul class="contact-list uk-margin-remove-bottom uk-padding-remove-bottom">
                <li>
                  <a href="https://www.facebook.com/thammasat.uni"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="https://www.youtube.com/user/PRTHAMMASAT"><i class="fab fa-youtube"></i></a>
                </li>
                <li>
                  <a href="https://twitter.com/thammasat_uni"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                  <a href="https://www.instagram.com/thammasat_official"><i class="fab fa-instagram"></i></a>
                </li>
                <a href="https://analytics.service.sci.tu.ac.th/eval/need2fix">ประเมินเว็ปไซต์</a> 
              </ul>
              
          </div>
      </div>
      <div>
          <p class="uk-text-lead uk-margin-remove-bottom">ติดต่อสอบถาม</p>
          <p class="uk-padding-remove-top uk-margin-remove-top"> อาคารบรรยายรวม 5 ชั้น 3 คณะวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยธรรมศาสตร์</p>
      </div>
  </div>
</div>

</div>
</div>
</div>

{% block script %}
<script type="text/javascript">
var app = new Vue({
el: '#app',
delimiters: ['[[', ']]'],
log:false,
data: function () {
return {}
}
})
</script>
{% endblock %}
</body>
</html>